# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Text to be shown in the URL for this item. Auto-populates based on the name field.', max_length=200, unique=True)),
                ('content', models.TextField(help_text='The content to display on the page. You may use Markdown.')),
            ],
        ),
    ]
