# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Whether or not to display this page as a link in the main site navigation.'),
            preserve_default=False,
        ),
    ]
